version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - 7700:7700
    volumes:
      - ./data.ms:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=masterKey
